### ISSUE TITLE
Discuss `aws-sdk` version in `package.json`

### ISSUE THREAD

**Issue by chilts** [chilts/nice-route53#19]
Probably prior to me knowing much, I added this in the `package.json`:

```
  "dependencies": {
    "aws-sdk": "^2.6.12"
  },
```

I think this means greater than or equal to 2.6.12, but less than 2.0.0 (from https://www.npmjs.com/package/semver#caret-ranges-123-025-004).

Should I just change this to be `^2` (or even `v2.0.0`) so it is more explicit that it just depends on any v2? Does it even matter? Perhaps all of this is a non-issue.

/cc @leorossi

**Comment by leorossi** [comment]
I don't think it means "less than `2.0.0`", you can check it on https://semver.npmjs.com/

The Route53 API didn't change since 2013, but `aws-sdk` package has been improved to support features or new geographic zones. I think this is a non issue, but it could worth to use a more updated version of `aws-sdk`

**Comment by chilts** [comment]
Oh cool, I've never seen https://semver.npmjs.com/ before.

Will close this out as "it's already doing the right thing with v2". Thanks for your thoughts and analysis.
